[package]
name = "baseline-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = "0.6"
tokio = { version = "1.25", features = ["full"] }

