[package]
name = "mio-tcp-client"
version = "0.1.0"
authors = ["sergey-melnychuk"]
edition = "2018"

[dependencies]
parsed = "0.1.6"
log = "0.4.8"
env_logger = "0.7.1"

[dependencies.mio]
version = "0.7.0"
features = ["os-poll", "tcp"]
